### ISSUE TITLE
Oasdiff does not recognize changes in Security Requirement Object

### ISSUE THREAD

**Issue by mstypsan** [oasdiff/oasdiff#175]
**Describe the bug**
Changes to an existing Security Requirement Object are not being recognized. 

**To Reproduce**
1. Create 2 different yaml specification files with security scheme
```
securitySchemes:
    petstore_auth:
      type: oauth2
      flows: 
        implicit:
          authorizationUrl: http://example.org/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets

```
where the first one (spec1.yaml) will have the following security object
```
security:
     - petstore_auth:
            - write:pets
            - read:pets
```
and the second one (spec2.yaml) will have the following security object
```
security:
     - petstore_auth:
            - write:pets
```
              
2. Run `oasdiff  -base spec1.yaml -revision spec2,yaml`
3. No differences are detected

**Expected behavior**
I believe that the differences should be detected and that it should be marked as a breaking change

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: N/A
