### ISSUE TITLE
malformed YAML structure for endpoints

### ISSUE THREAD

**Issue by peruzzof** [oasdiff/oasdiff#183]
**Describe the bug**
When using the diff with YAML format the Endpoints/Modified structure has a malformed YAML structure because the key is not a string.

**To Reproduce**
1. Run `oasdiff.exe -format=text -base petstore.yaml -revision petstore_2.yaml -format yaml`
2. We will receive an malformed YAML because key under endpoints/modified 2 strings as identifier:
```
paths:
    modified:
        /pets:
            operations:
                modified:
                    GET:
                        parameters:
                            added:
                                query:
                                    - page_size
endpoints:
    modified:
        ?   method: GET
            path: /pets
        :   parameters:
                added:
                    query:
                        - page_size
```

**Expected behavior**
The structure under endpoints/modified can be converted to an array with one "id" structure and the "changes", in this case it will be presented as: 
```
endpoints:
- modified:
  - id:
    - method: GET
      path: "/pets"
    changes:
    - parameters:
      - added:
        - query:
          - page_size
```

A second alternative is to exclude this structure from the YAML, using a flag or by default.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 1.3.1

**Additional context**
petstore.yaml at https://gist.githubusercontent.com/peruzzof/affe59e40f5b257751462775775b7b7c/raw/b0d2299c3a3eba76bcb96bf9258bef68aaf50f74/petstore.yaml

petstore_2.yaml at https://gist.githubusercontent.com/peruzzof/affe59e40f5b257751462775775b7b7c/raw/b0d2299c3a3eba76bcb96bf9258bef68aaf50f74/petstore_2.yaml
