### ISSUE TITLE
how to integration with gitlab?

### ISSUE THREAD

**Issue by blakejunqi** [oasdiff/oasdiff#220]
Hello,I would like to ask a question,how to integrate with gitlab?

**Comment by effoeffi** [comment]
Hello @blakejunqi,
I am not using Gitlab, but it should be similar to other CI tools:
- Add a build step (stage in Gitlab) to the config file `.gitlab-ci.yml` and name it for example `breaking-changes`
- Create an OpenAPI spec file as part of the build (revision file)
- Add a `breaking-changes` script and provide base and revision files to it
Here is the concept it will require refinements:
```
stages:
  - build
  - breaking-changes
  - release
  
### Other stages code

breaking-changes:
  image: tufin/oasdiff
  script:
  - |
      oasdiff -check-breaking -base base.yaml -revision revision.yaml
```

Please, test it and share the results
