### ISSUE TITLE
2x same param name in `components.parameters` triggers diff for identical `base` and `revision`

### ISSUE THREAD

**Issue by raphaelhuefner** [oasdiff/oasdiff#352]
**Describe the bug**

2 parameter definitions in the `components.parameters` section with the same parameter `name`, but with differing `schema` and `description` trigger diff output for both, `oasdiff summary` and `oasdiff diff`, especially when `base` and `revision` are identical.

**To Reproduce**

Note that the attached [oasdiff_bug_different_component_same_parameter.zip](https://github.com/Tufin/oasdiff/files/12226302/oasdiff_bug_different_component_same_parameter.zip) contains the example minimal OAS file for the following steps.

- use `oasdiff` version 1.7.1 (I've seen it with 1.7.0 as well, but didn't try any other versions.)
- (extract from ZIP file or) create a file `oasdiff_bug_different_component_same_parameter.yaml` with the following content:

```
openapi: 3.0.3

components:
  parameters:
    differentComponentName_A:
      name: sameParamName
      in: query
      required: false
      schema:
        type: string
        enum:
          - option_1
          - option_2
        default: option_1
      description: Let's mention both options, option_1 and option_2.
    differentComponentName_B:
      name: sameParamName
      in: query
      required: false
      schema:
        type: string
        enum:
          - option_1
        default: option_1
      description: Let's mention the only option, option_1.
```
- run `oasdiff summary oasdiff_bug_different_component_same_parameter.yaml oasdiff_bug_different_component_same_parameter.yaml` (Note that `base` and `revision` are the very same file!)
- receive
```
diff: true
details:
    parameters:
        modified: 1
```
- run `oasdiff diff oasdiff_bug_different_component_same_parameter.yaml oasdiff_bug_different_component_same_parameter.yaml` (Note that `base` and `revision` are the very same file!)
- receive
```
components:
    parameters:
        modified:
            query:
                sameParamName:
                    description:
                        from: Let's mention both options, option_1 and option_2.
                        to: Let's mention the only option, option_1.
                    schema:
                        enum:
                            deleted:
                                - option_2
```
(Sometimes the diff is shown in reverse, i.e. as _added_ enum option.)

**Expected behavior**

- For `oasdiff summary` I would expect to see
```
diff: false
```
as output.

- For `oasdiff diff` I would expect an empty output.

**Desktop:**

- OS: macOS (AFAICT irrelevant)

**Additional context**

- I checked https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#components-object and did not find any rule which prohibits multiple, differing, parameter definitions for the same parameter `name`.
- I can understand how one could argue that such a constellation might be less than ideal. OTOH I ask to also understand the other side, where the same parameter `name` has a different meaning (and hence a different declaration) in different contexts.
- I don't think it is `oasdiff`'s role to enforce any rules about parameter naming, that would be a linter's job.
