### ISSUE TITLE
Wrong go version format

### ISSUE THREAD

**Issue by obochurkin** [oasdiff/oasdiff#461]
**Describe the bug**
`go.mod:3: invalid go version '1.21.5': must match format 1.23`

**To Reproduce**
Running mjs script to get the diff between two swagger docs.
`open-api.mjs`
```
#!/usr/bin/env zx

async function main() {
  await $`go install github.com/tufin/oasdiff@latest`;
}
main();
```
This script runs in GitHub action:
```
...
jobs:
  build-docs:
    runs-on: ubuntu-latest
    ...
    steps:
      - name: Set up Go    
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'    

      - name: Install zx
        run: |
          npm i -g zx
          
      - name: Run zx script
        run: |
          zx ./.github/workflows/scripts/open-api.mjs  --token="${{ }}" --repo="${{ }}"
```
Output:
```
$ go install github.com/tufin/oasdiff@latest
go: downloading github.com/tufin/oasdiff v1.10.2
go: github.com/tufin/oasdiff@latest (in github.com/tufin/oasdiff@v1.10.2): go.mod:3: invalid go version '1.21.[5](https://github.com/.../.../actions/runs/.../job/...#step:7:6)': must match format 1.23
file:///opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

Error: Output [Error]: go: downloading github.com/tufin/oasdiff v1.10.2
go: github.com/tufin/oasdiff@latest (in github.com/tufin/oasdiff@v1.10.2): go.mod:3: invalid go version '1.21.5': must match format 1.23
    at main (file:///home/runner/work/.../.../.github/workflows/scripts/open-api.mjs:77:10)
    exit code: 1
    at ChildProcess.<anonymous> (file:///opt/hostedtoolcache/node/1[6](https://github.com/.../.../actions/runs/.../job/...#step:7:7).20.2/x64/lib/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:1[7](https://github.com/.../.../actions/runs/.../job/...#step:7:8)) {
  _code: 1,
  _signal: null,
  _stdout: '',
  _stderr: 'go: downloading github.com/tufin/oasdiff v1.[10](https://github.com/.../.../actions/runs/.../job/...#step:7:11).2\n' +
    "go: github.com/tufin/oasdiff@latest (in github.com/tufin/oasdiff@v1.10.2): go.mod:3: invalid go version '1.21.5': must match format 1.23\n",
  _combined: 'go: downloading github.com/tufin/oasdiff v1.10.2\n' +
    "go: github.com/tufin/oasdiff@latest (in github.com/tufin/oasdiff@v1.10.2): go.mod:3: invalid go version '1.21.5': must match format 1.23\n"
}
Error: Process completed with exit code 1.
```

**Expected behavior**
Successful installation due to expected go version format.

**Desktop (please complete the following information):**
 - GitHub actions
