### ISSUE TITLE
Endpoints with query parameters attached are currently considered as different with the same ones without them in the URL. It would be good to have a flag of some sort to ignore query parameters attached to the URL when computing the diff.

### ISSUE THREAD

**Issue by dnighvn** [oasdiff/oasdiff#468]
**Is your feature request related to a problem? Please describe.**
Consider the endpoint `/api/config` that has a query parameter **providerType**.
We can either define as:
```yaml
/api/config:
    put:
      tags:
        - a-tag
      summary: Update config
      description: 'Update config for a given provider type [...]'
      operationId: updateConfigUsingPUT
      parameters:
        - name: providerType
          in: query
          description: providerType
          required: true
...
```
or also:
```yaml
/api/config{?providerType}:
    put:
      tags:
        - a-tag
      summary: Update config
      description: 'Update config for a given provider type [...]'
      operationId: updateConfigUsingPUT
      parameters:
        - name: providerType
          in: query
          description: providerType
          required: true
...
```
However, running **oasdiff**, it consider as two different endpoints. This scenario can even be more complicated in the presence of more parameters, and they could even be optionally added to the path.

I created a small repository testing this behavior: https://github.com/dnighvn/oasdiff-tests

<img width="1081" alt="image" src="https://github.com/Tufin/oasdiff/assets/149076889/768f59f7-181f-4650-b68f-002816c5e178">

Running, it gives this response:

```json
{
  "paths": {
    "added": [
      "/api/config"
    ],
    "deleted": [
      "/api/config{?providerType}"
    ]
  },
  "endpoints": {
    "added": [
      {
        "method": "DELETE",
        "path": "/api/config"
      },
      {
        "method": "PUT",
        "path": "/api/config"
      }
    ],
    "deleted": [
      {
        "method": "DELETE",
        "path": "/api/config{?providerType}"
      },
      {
        "method": "PUT",
        "path": "/api/config{?providerType}"
      }
    ]
  },
  "components": {}
}
```

Bringing back **{?providerType}** to spec_revision's path, the response is **null**.

**Describe the solution you'd like**
Since it is optional to define query parameters in the path, and they are being treated differently, but in practice they work as the same, I believe **oasdiff** could have a flag to ignore this kind of difference, so we know that we have the same specs.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by reuvenharrison** [comment]
Hi @dnighvn.
Query params should not appear in the path of the OpenAPI spec, only under `parameters`, like this:
```
/api/config:
    put:
      parameters:
        - name: providerType
          in: query
          description: providerType
          required: true
```
See https://swagger.io/docs/specification/describing-parameters/#query-parameters.

Why are you also adding the query parameter to the path?
Is this auto-generated by some tool?
