### ISSUE TITLE
feat: support external metadata

### ISSUE THREAD

**Issue by bdoughan-snow** [oasdiff/oasdiff#494]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to externalize the oasdiff metadata.  Currently you can leverage the `x-stability-level` extension within an OpenAPI document, but care must be take to ensure any metadata added to the OpenAPI document is not released to the public.

**Describe the solution you'd like**
I am looking for something equivalent to what is offered by the Spectral linter.  In the example below this metadata is saying that for the GET operation in the /api/pet-store/v1/pets endpoint turn off the paths-summary-get rule.

```
extends: 
  - ./rest-ruleset.yamloverrides:
  - files: 
      - "**#/paths/~1api~1pet-store~1v1~1pets/get"
    rules:
      paths-summary-get: off
```

**Describe alternatives you've considered**
Currently we are considering using the inline extensions with a Spectral linter rule to flag when this extension is present within an OpenAPI document.

**Additional context**
We would like this functionality to work with oasdiff-action.
