### ISSUE TITLE
basePath and servers.ulr support

### ISSUE THREAD

**Issue by codeFather2** [oasdiff/oasdiff#512]
**Is your feature request related to a problem? Please describe.**
I tried comparing the API specification version 2, which has a `basePath` field defined, but their comparison does not take this field into account. I also tried to compare the version 3.* specification, but the `servers.url` field is also not taken into account in the comparison of 2 specifications, for example, if it is defined in one file, and in the other the base path is defined specifically for each path as a prefix
e.g.
v2 with `basePath`
```yaml
basePath: /v1
paths:
  /entry/check:
    ...
  /entry/enter:
    ...
```
v2 without `basePath`
```yaml
paths:
   /v1/entry/check:
    ...
   /v1/entry/enter:
    ...
```
v3 with `servers.url`
```yaml
servers:
    -url: /v1
paths:
  /entry/check:
    ...
  /entry/enter:
    ...
```
v3 without `servers.url`
```yaml
paths:
  /v1/entry/check:
    ...
  /v1/entry/enter:
    ...
```

**Important**
in swagger specs from version 3, you can provide `servers.url` by variables with default values
```
servers:
  - description: Production
    url: {basePath}
    variables:
      basePath:
        default: /v1
```

**Describe the solution you'd like**
If it's possible can we add support for both versions of spec and comparison between version 2 with `basePath` and version 3.* with `servers.url` fields. 
The way i see it is to use this prefix field from base and try remove it from revision spec if possible or apply it to base spec (it feels more difficult to do and can lead to undesirable effects). If there are base paths in both places, compare them with each other

**Describe alternatives you've considered**
*In progress*

**Comment by codeFather2** [comment]
It is also necessary to take into account that the `servers.url` may contain the host
```yaml
servers:
  - description: Production
    url: https://api.test.com{basePath}
    variables:
      basePath:
        default: /v1
 ```
