### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mitar** [oasdiff/oasdiff#53]
**Describe the bug**

It seems when one spec has oauth2 flow and the other does not, I get `panic: runtime error: invalid memory address or nil pointer dereference`.

**To Reproduce**

I have in one spec:

```
  securitySchemes:
    AccessToken:
      type: oauth2
      flows:
        ...
```

and in the other:

```
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
```

**Expected behavior**

I get some diff.

**Additional context**

I think the problem is in this code inside `getOAuthFlowsDiffInternal`:

```
        if flows1 == nil && flows2 == nil {
                return nil
        }

        result := OAuthFlowsDiff{}

        result.ExtensionsDiff = getExtensionsDiff(config, flows1.ExtensionProps, flows2.ExtensionProps)
```

The `if` checks only if both of flows are `nil`, but it seems in my case one is `nil` and the other is not, so once you get to `flows1.ExtensionProps`, if `flows1` is `nil`, you get a panic.
