### ISSUE TITLE
Webhooks diff

### ISSUE THREAD

**Issue by gcatanese** [oasdiff/oasdiff#634]
**Describe the bug**
When generating the `diff` between specs that contain webhooks I notice the following:

### Output start with extensions
Should `extensions` be replaced by `webhooks`?
```
extensions:
    modified:
        webhooks:
            - oldValue: null
              value:
```

### Deleted properties without error or warning
Request attributes are dropped, I would expect a warning to inform about the (potential?) breaking change
```
TransferData:
                properties:
                    added:
                        - categoryData
                    deleted:
                        - platformPaymentType
                        - pspPaymentReference

```

**To Reproduce**
```
oasdiff diff https://raw.githubusercontent.com/Adyen/adyen-openapi/refs/heads/main/yaml/BalancePlatformTransferNotification-v3.yaml \ 
https://raw.githubusercontent.com/Adyen/adyen-openapi/refs/heads/main/yaml/BalancePlatformTransferNotification-v4.yaml
```

**Expected behavior**
1. Replace `extensions` with `webhooks`?
2. Introduce `error` and `warning`

**Desktop (please complete the following information):**
 - OS: macOS
