### ISSUE TITLE
"oasdiff breaking" and "oasdiff changelog" don't find changes in enums

### ISSUE THREAD

**Issue by dtujmer** [oasdiff/oasdiff#705]
**Describe the bug**

When you run `oasdiff breaking <base> <revision>` or `oasdiff changelog <base> <revision>`, you don't get changes in enums. However, these changes are visible in `oasdiff diff`.

**To Reproduce**

1. `oasdiff changelog <spec1> <spec2>` (or `oasdiff breaking`)
2. Spec 1: https://docs.microblink.com/documentation/self-hosted/3.15.0/static/openapi.json
3. Spec 2: https://docs.microblink.com/documentation/self-hosted/4.2.0/static/openapi.json
4. When you `grep` the output for `enum`, there are no results.

**Expected behavior**

If you take a look at `.components.schemas.ProcessingStatus`, you'll see that the enum in the base (v3.1.5) contains `CLASS_FILTERED`, `UNSUPPORTED_CLASS`, and `UNSUPPORTED_BY_LICENSE`.

In the revision (v4.2.0), you will see that it does not contain these values. Instead, it contains `DOCUMENT_FILTERED` and `UNSUPPORTED_DOCUMENT`. And the value `UNSUPPORTED_BY_LICENSE` is removed.

This is confirmed by the output of `oasdiff diff <spec1> <spec2>`:

```
            ProcessingStatus:
                enum:
                    added:
                        - DOCUMENT_FILTERED
                        - UNSUPPORTED_DOCUMENT
                    deleted:
                        - CLASS_FILTERED
                        - UNSUPPORTED_CLASS
                        - UNSUPPORTED_BY_LICENSE
```

This issue persists even if you bundle a dereferenced schema. For example, if you run `redocly bundle --dereferenced <schema> -o <dereferenced_schema>`, and delete the `components` section entirely, and then compare schemas like that (doing the same with the other schema), it *still* won't find the differences in enums.

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.4.1
 - `oasdiff` version: 1.11.4
