### ISSUE TITLE
-format text fails to report server changes

### ISSUE THREAD

**Issue by zeno-ce** [oasdiff/oasdiff#88]
**Describe the bug**
When running oasdiff with the `-format text` option it fails to report certain changes. 

**To Reproduce**
```
$ ./oasdiff -fail-on-diff -breaking-only -format text -base "./current.json" -revision "./new.json"
No endpoint changes
$ echo $?
1
```

Executing the same command with `-format yaml` shows changes to servers and paths:
```
paths:
    modified:
        /foo:
            servers:
                deleted:
                    - ...
servers:
    deleted:
        - ...
```

**Expected behavior**
Report changes to paths and deleted servers in text format. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
